### ISSUE TITLE
Switching between different versions of the format

### ISSUE THREAD

**Issue by kkalb** [100phlecs/tailwind_formatter#10]
Elixir: 1.14.1
Erlang: 25.1.2
tailwind_formatter: 0.2.2

When I run
```elixir
mix format --dot-formatter .tailwind_formatter.exs
```
with the following formatter config .tailwind_formatter.exs

```elixir
[
  plugins: [TailwindFormatter],
  inputs: [
    "*.{heex}",
    "{lib}/**/*.{heex}"
  ]
]
```
I tested this with many different combinations of 
```elixir
  plugins: [TailwindFormatter, Phoenix.LiveView.HTMLFormatter]
  plugins: [Phoenix.LiveView.HTMLFormatter]
  plugins: [TailwindFormatter]
```
but nothing seems to work for me.

TailwindFormatter constantly switches between the following orders
```html
class="bg-colorGreen-400 inline-block rounded-lg px-3 py-3 text-center text-sm font-semibold text-white shadow-sm transition duration-200 hover:bg-colorGreen-500 hover:shadow-md focus:bg-colorGreen-600 focus:ring-colorGreen-500 focus:shadow-sm focus:ring-4 focus:ring-opacity-50"
```
```html
class="bg-colorGreen-400 inline-block rounded-lg px-3 py-3 text-center text-sm font-semibold text-white shadow-sm transition duration-200 hover:bg-colorGreen-500 hover:shadow-md focus:ring-colorGreen-500 focus:bg-colorGreen-600 focus:shadow-sm focus:ring-4 focus:ring-opacity-50"
```

Reduced to the important stuff:

```html
class="focus:bg-colorGreen-600 focus:ring-colorGreen-500"
class="focus:ring-colorGreen-500 focus:bg-colorGreen-600"
```
Like this, even if I would not care about this order, I can not use it in CI.

This happens with a few files more. I can also share the differences, if needed.
Maybe it is worth mentioning that I also use recode, prettier, stylelint, Phoenix.LiveView.HTMLFormatter, credo. All with the integrations in VSC. I would not exclude some interfering extensions but for now I hope you can spot and fix this problem.

Keep up the good work!

**Comment by kkalb** [comment]
Edit: I created a fork, branch and committed a new test that shows the problem. The first run is valid but the second run of format() fails.
https://github.com/100phlecs/tailwind_formatter/compare/master...kkalb:tailwind_formatter:add-larger-tailwind-test

**Comment by 100phlecs** [comment]
Thanks for the bug report!
I appreciate the attention to detail and the provided test.

The issue was how the variants and classes were split; the lists were in **reverse order.**

This caused me issues in the past, [so I changed how the `Enum.sort` worked](https://github.com/100phlecs/tailwind_formatter/commit/24464f8a8a4a0345e87dab3a7f4ef859f828e9a3), even though [the docs don't recommend it](https://hexdocs.pm/elixir/1.14/Enum.html#sort/2):

```
The sorting algorithm will be stable as long as the given function returns true for values considered equal.
```

Now I can change it back :) 

An additional note:

This formatter can only sort default tailwind classes. So your own defined classes like `bg-colorGreen-500` are considered "unknown" and thus has an ordering value of `-1` (i.e. push it to the front of the sort).

In the future, it may be possible to ship a binary that "reads" your `tailwind.config.js` to also sort your defined classes. We'll see!

**Comment by 100phlecs** [comment]
With the latest version, your custom defined classes should be pushed toward the front, but maintain the same order.

Please let me know if you run into any issues :)

**Comment by kkalb** [comment]
Perfect! I just pushed on the fork, doing some refactoring to enable me to also fix problems myself.
Tomorrow I merge your changes into my branch.
The recent commits are kinda WIP but the tests still pass (and the buggy tests still fail).

Maybe have a look to the new added test, there
```html
xs:p-0
```
formats to
```html
p-0:xs
```
and I wonder if this is a bug or valid TailwindCSS code.

**Comment by 100phlecs** [comment]
As far as I know, `xs` as a screen size isn't included in defaults.
https://tailwindcss.com/docs/screens

Is `xs` defined as a custom screen within your `tailwind.config.js`?

**Comment by 100phlecs** [comment]
I added your test to the `master` branch https://github.com/100phlecs/tailwind_formatter/commit/db1328cf5a8fb00d22d7f750a0da4e5b95172833 and it successfully passes, so I'm not sure why it isn't passing on your fork

**Comment by kkalb** [comment]
Perfect!
Since I can not create a branch and my fork contains some other unnecessary changes, here my suggested changes:

```elixir
  defp separate(class_list) do
   Enum.split_with(class_list, &(not variant?(&1))
  end
```
split_with splits a list into a tuple of two lists based on the value of the function.

**Comment by 100phlecs** [comment]
That is definitely a cleaner solution than what I've implemented, thanks for the suggestion :) 
I've switched to a variant of your suggestion with the latest commit.

I suppose we can consider this issue resolved; please feel free to reopen or create a new one if you run into additional issues!
