### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by numso** [100phlecs/tailwind_formatter#57]
Hello! First off, thanks for this package. My team uses it and we think it's really great!

Any chance we could get a new version published now that https://github.com/100phlecs/tailwind_formatter/pull/52 has been merged? I don't know if you had anything else planned before bumping the version. But the ability to format classes in function components would, by itself, be very helpful for us.

**Comment by RodolfoSilva** [comment]
@100phlecs, that will help us here too.
Do you have time to plan a new version? I imagine you must be pretty busy.

**Comment by numso** [comment]
Until a new version is published, you can pin the dependency to a specific git hash. Here's the change we made to our mix.exs to make that happen:

```diff
- {:tailwind_formatter, "~> 0.4.0", only: [:dev, :test], runtime: false},
+ {:tailwind_formatter, git: "https://github.com/100phlecs/tailwind_formatter", ref: "3896f735be23ea4d6c15f8e9e39b65430d972925", only: [:dev, :test], runtime: false},
```

**Comment by 100phlecs** [comment]
Released the new version, thanks for your patience!
