### ISSUE TITLE
Multi Formatter

### ISSUE THREAD

**Issue by ddengler** [100phlecs/tailwind_formatter#9]
Thanks for the formatter. Exactly what I was looking for.

I created an alternative workaround for the mix limitations prior to the unreleased 1.15 for my use case looking like this, so I can still use this properly with my vscode plugin formatting files on save:

``` elixir
defmodule MultiFormatter do
  if Version.match?(System.version(), ">= 1.13.0") do
    @behaviour Mix.Tasks.Format
  end

  def features(_opts) do
    [sigils: [:H], extensions: [".heex"]]
  end

  def format(contents, opts) do
    Phoenix.LiveView.HTMLFormatter.format(contents, opts) |> TailwindFormatter.format(opts)
  end
end
```

Maybe this is useful to you or could provide a basis for a more generic workaround in you project.

**Comment by mjyoung** [comment]
@ddengler Does this work for you to automatically format tailwind classes in heex files? I can't get vscode to automatically format these (need to manually run `mix format`). what do your settings look like for `[phoenix-heex]`?

**Comment by ddengler** [comment]
```
{
    "html": [
      "HTML (EEx)",
      "htm",
      "html"
    ]
  },
  "files.associations": {
    "*.js": "javascript",
    "*.ex": "elixir",
    "*.exs": "elixir",
    "*.html.eex": "html-eex",
    "*.html.leex": "html-eex",
    "*.eex": "html-eex",
    "*.leex": "html-eex",
    "*.heex": "phoenix-heex",
    "*.html.heex": "phoenix-heex",
  },
  "tailwindCSS.experimental.classRegex": [
    "class:\\s*\"([^\"]*)\""
  ],
  "tailwindCSS.includeLanguages": {
    "html-eex": "html",
    "phoenix-heex": "html",
    "html": "html",
    "elixir": "html",
    "eex": "html"
  },
  "editor.formatOnSave": true,
  "[phoenix-heex]": {
    "editor.defaultFormatter": "animus-coop.vscode-elixir-mix-formatter"
  },
}
```

These are all my possibly relevant settings. Also the animus-coop.vscode-elixir-mix-formatter is installed as a plugin to auto-run the mix format task. Hope this helps?

**Comment by 100phlecs** [comment]
Sure! Cleaner solution than the bash script.
If you're using this library you are definitely using phoenix/heex so may as well include it as a dependency.

Thanks for the provided file. I'll include it along with new instructions.
